config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
  validates :user_id, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets

  validates :name, presence: true
  validates :handle, presence: true
  validates :email, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    render template: 'dashboard/index.html.erb', locals: {
      tweets: Tweet.all[0..24],


    }
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    render template: 'tweets/index.html.erb', locals: {
      tweets: Tweet.all,
      users: User.all,
      
      title: "All Tweets"
    }
  end

  def show
    if Tweet.exists?(params[:id])
      tweet = Tweet.find(params[:id])
      render template: 'tweets/show.html.erb', locals: {
        tweet: tweet
      }
    else render html: "Tweet Not Found.", status: 404
    end
  end

  def new
    render locals: {
      tweet: Tweet.new
    }
  end

  def create
    tweet = Tweet.new
    tweet.body = params[:tweet][:body]
    if tweet.save
      redirect_to tweet_path(tweet)
    else
      flash[:alert] = "Tweet not saved due to errors."
      render template: '/tweets/new.html.erb', locals: {
        tweet: tweet
      }
    end
  end

  def edit
    render locals: {
      tweet: Tweet.find(params[:id])
    }
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.body = params[:tweet][:body] if params[:tweet][:body].present?
    if tweet.save
      redirect_to tweet_path(tweet)
    else
      render template: '/tweets/new.html.erb', locals: {
        tweet: tweet
      }
    end
  end

  def destroy
    if Tweet.exists?(params[:id])
      Tweet.destroy(params[:id])
      flash[:notice] = "Tweet deleted"
      redirect_to tweet_path(tweet)
    else
      flash[:alert] = "Tweet was not deleted due to an error."
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render template: 'users/index.html.erb', locals: {
      users: User.all,
      title: "All Users"
    }
  end

  def show
    if User.exists?(params[:id])
      user = User.find(params[:id])
      render template: 'users/show.html.erb', locals: {
        user: user,
      }
    else
      render html: "User Not Found", status: 404
    end
  end

  def new
    render locals: {
      user: User.new
    }
  end

  def create
    user = User.new
    user.name = params[:user][:name]
    user.handle = "@" + params[:user][:handle]
    user.email = params[:user][:email]
    if user.save
      redirect_to user_path(user)
    else
      flash[:alert] = "User was not created. Please make sure all fields are filled out."
      render template: '/users/new.html.erb', locals: {
        user: user
      }
    end
  end

  def edit
    render locals: {
      user: User.find(params[:id])
    }
  end

  def update
    user = User.find(params[:id])
    user.name = params[:user][:name] if params[:user][:name].present?
    user.handle = params[:user][:handle] if params[:user][:handle].present?
    user.email = params[:user][:email] if params[:user][:email].present?
    if user.save
      redirect_to user_path(user)
    else
      render template: '/users/new.html.erb', locals: {
        user: user
      }
    end
  end

  def destroy
    if User.exists?(params[:id])
      User.destroy(params[:id])
      flash[:notice] = "User deleted."
      redirect_to user_path(user)
    else
      flash[:alert] = "There was an error. Please try again."
    end
  end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
  def index
    render template: 'users/index.html.erb', locals: {
      users: User.all,
      title: "All Users"
    }
  end

  def show
    if User.exists?(params[:id])
      user = User.find(params[:id])
      render template: 'users/show.html.erb', locals: {
        user: user,
      }
    else
      render html: "User Not Found", status: 404
    end
  end

  def new
    render locals: {
      user: User.new
    }
  end

  def create
    user = User.new
    user.name = params[:user][:name]
    user.handle = params[:user][:handle]
    user.email = params[:user][:email]
    if user.save
      redirect_to user_path(user)
    else
      flash[:alert] = "User was not created. Please make sure all fields are filled out."
      render template: '/users/new.html.erb', locals: {
        user: user
      }
    end
  end

  def edit
    render locals: {
      user: User.find(params[:id])
    }
  end

  def update
    user = User.find(params[:id])
    user.name = params[:user][:name] if params[:user][:name].present?
    user.handle = params[:user][:handle] if params[:user][:handle].present?
    user.email = params[:user][:email] if params[:user][:email].present?
    if user.save
      redirect_to user_path(user)
    else
      render template: '/users/new.html.erb', locals: {
        user: user
      }
    end
  end

  def destroy
    if User.exists?(params[:id])
      User.destroy(params[:id])
      flash[:notice] = "User deleted."
      redirect_to user_path(user)
    else
      flash[:alert] = "There was an error. Please try again."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<section class='all-tweets'>
  <header>
    <h1>Welcome to Twitter</h1>
    <h3>Latest <%= tweets.count %> Tweets</h3>
  </header>

  <% tweets.each do |tweet| %>
    <p> <%= tweet.user.handle %></p>
      <p><%= link_to tweet.body, tweet_path(tweet) %> </p>
  <% end %>
<article class='one-tweet-info'
  <p class='header'>
    <div = 'one-users-tweet'>
    </div>
  </p>
  </article>
    <article class='tweet'>
      <p class='body'>
        <div = 'one-tweet'>
        </div>
      </p>
    </article>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>
        <%= local_assigns[:title] || 'Twitter' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <header class='main-header'>
      <div class='container'>
        <div class='row'>
          <div class='col-xs-4'>
              <h1>Twitter</h1>
            </div>
            <div class='col-xs-3 col-xs-offset-1'>
              <img src='https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Twitter_bird_logo_2012.svg/945px-Twitter_bird_logo_2012.svg.png'/>
            </div>
            <div class='col-xs-4'>
            <%= render 'shared/nav' %>
          </div>
          </div>
        </div>
      </div>
    </header>
    <body>
    <div class='container'>
      <div class='row'>
        <div class='col-xs-4 col-xs-offset-4'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav>
    <div class='col-xs-4'><%= link_to "Home", root_path %></div>
    <div class='col-xs-4'><%= link_to "Users", users_path %></div>
    <div class='col-xs-4'><%= link_to "Tweets", tweets_path %></div>
</nav>

app/views/tweets/_form.html.erb
<div class="all_form">
<div class="row">
  <h4><%= form_title %></h4>
</div>
<div class="row">
  <% if tweet.errors.any? %>
    <% tweet.errors.full_messages.each do |msg| %>
      <p> <%= msg %></p>
    <% end %>
  <% end %>
</div>

    <%= form_for(tweet) do |f| %>
    <div class="row">
    <div class="input-group">
      <label for="id">User</label>
      <%= f.select :user_id, options_from_collection_for_select(User.all, :id, :name) %>
    </div>
      <div class="row">
        <div class="input-group">
          <label for="body">Body</label>
          <%= f.text_field :body, placeholder: "Tell the world what you have to say!" %>
        </div>
      </div>
      <div class="row">
        <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
</div>
</div>
    <% end %>

app/views/tweets/edit.html.erb
<%= render 'form', tweet: tweet, form_title: "Edit Tweet" %>

app/views/tweets/index.html.erb
<section class='all-tweets'>
  <header>
    <h3>All <%= tweets.count %> Tweets
    <button type="button" class="btn btn-default"><%= link_to "New Tweet", new_tweet_path(tweets) %></button>
  </h3>
</header>
</div>
</div>

  <% tweets.each do |tweet| %>
    <div class='one-tweet'><p> <%= tweet.user.handle %></p>
    <p><%= link_to tweet.body, tweet_path(tweet) %> </p>
  <% end %>
</div>
</section>

app/views/tweets/new.html.erb
<%= render 'form', tweet: tweet, form_title: "New Tweet" %>

app/views/tweets/show.html.erb
<section class='one-tweet'>
  <header>
    <h3><%= link_to tweet.user.name, user_path(tweet.user) %>'s Tweet</h3>

  </header>
  <p>
    <%= tweet.body %>
  </p>
</section>

app/views/users/_form.html.erb
<div class="row">
  <h4><%= form_title %></h4>
</div>

<div class="row">
  <% if user.errors.any? %>
    <% user.errors.full_messages.each do |msg| %>
      <p> <%= msg %></p>
    <% end %>
  <% end %>
</div>
  <div class="user-content">
    <%= form_for(user) do |f| %>

        <div class="input-group">
          <label for="name">Name</label>
          <p>
          <%= f.text_field :name, placeholder: "What's your name?" %>
        </div>

      <div class="input-group">
        <label for="handle">Handle</label>
        <p>
        <%= f.text_area :handle, placeholder: "@handle" %>
      </div>
      <div class="input-group">
        <label for="email">Email</label>
        <p>
        <%= f.text_area :email, placeholder: "What's your email address?" %>
      </div>
      <div class="row">
        <div class="actions">
        <%= f.submit %>
      </div>
    </div>
    </div>
  </div>
    <% end %>

app/views/users/edit.html.erb
<%= render 'form', user: user, form_title: "Edit User" %>

app/views/users/index.html.erb
<section class='all-users'>
  <header>
    <h3>All <%= users.count %> Users</h3>
    <button type="button" class="btn btn-default"><%= link_to "New User", new_user_path(users) %></button>
  </header>
  <p>
  <% users.each do |user| %>
    <p> <%= link_to user.name, user_path(user) %> <%= user.handle %> </p>
  <% end %>
<article class='one-user-info'
  <p class='header'>
  </p>
  </article>
      </p>
    </article>
</section>

app/views/users/new.html.erb
<%= render 'form', user: user, form_title: "New User" %>

app/views/users/show.html.erb
<section class='one-user'>
  <header>
    <h3><%= user.name %>'s Profile</h3>
    <p><%= user.handle %></p>
    <button type="button" class="btn btn-default"><%= link_to "Edit Profile", edit_user_path(user) %></button>
  </header>
  <p>
    <%= "No Tweets" if user.tweets.empty? %>
    <% user.tweets.each do |t| %>
      <p><%= link_to t.body, tweet_path(t) %></p>
    <% end %>
  </p>
</section>